### ISSUE TITLE
[Function]建议增加视频播放详情功能

### ISSUE THREAD

**Issue by DKYzz** [ScorpioPlayer/Feedback#12]
建议增加视频播放详情功能浮窗，能看到现在音频，视频流的解码策略，现播放视频的码流等功能~

**Comment by bosxixi** [comment]
目前是在 右键菜单=>杂项=>UI/UX=>在标题栏上显示视频音频解码信息/显示实时比特率信息
短期不会添加， 未来可能加

**Comment by DKYzz** [comment]
> 目前是在右键菜单=>杂项=> UI / UX =>在标题栏上显示视频音频解码信息/显示实时比特率信息
> 浮窗短期不会添加，未来可能加

标题上的信息有点含糊，例如在设置里开启了视频软解，音频关闭软解后，标题依旧显示视频与音频都是软解，有点迷糊...看不懂...

**Comment by bosxixi** [comment]
感谢您的反馈。随着v2.10.1188.0/70更新，解码设置更加清晰，添加了浮动播放信息，请告诉我您是否有更多的改进意见。

![image](https://github.com/ScorpioPlayer/Feedback/assets/12491547/2735990e-3984-4c7e-8cd7-b7eb96fdda95)

![image](https://github.com/ScorpioPlayer/Feedback/assets/12491547/5b524b78-a42b-4480-9327-2190cb336822)
