### ISSUE TITLE
XboxOneX and HDR

### ISSUE THREAD

**Issue by Dreakert** [ScorpioPlayer/Feedback#13]
Hello in the latest update on the Xbox one X it deactivated HDR with DLNA, before it worked excellent only plays 4k without HDR

**Comment by balvolkan** [comment]
I bought software to watch hdr movies, however it does not support hdr!

**Comment by bosxixi** [comment]
Hello:

![image](https://github.com/ScorpioPlayer/Feedback/assets/12491547/40f9616c-5215-4a74-a34d-614fcb79a967)


On Xbox Device recommend to use Game Mode and HDR Tone Mapping feature:

https://blog.scorpioplayer.com/blog/how-to-use-hdr-tone-mapping-feature-for-scorpio-player-app/

Game Mode:

https://blog.scorpioplayer.com/blog/scorpio-player-on-xbox-series-sx-game-mode/
