### ISSUE TITLE
XBox One X playback issue with 3 Terabyte WD Elements External 

### ISSUE THREAD

**Issue by DaytonaXBoxGuy** [ScorpioPlayer/Feedback#14]
I have been using several different Western Digital external drives with My XBox One X and noticed a very strange problem recently with one of my drives. It is partitioned with GPT (NTFS) and 3 TB in capacity. There is still nearly 300 Gigabytes free, but nearly every new .MKV file I have copied to the drive will throw an error in Scorpio Player "Can Not Open File". If I copy the exact same file to another drive it plays fine. I have scanned the drive with Scandisk and Windows 10 drive utility for errors and it finds none. I can play the files on that drive fine from a computer with no errors. There is something about this particular disk drive that Scorpio player just does not like at all. Other movies on the same disk drive play fine on Xbox One X / Scorpio player. It is just the newer files that all throw the error. Any ideas of what is going on here. This only started happening about 3 weeks ago. Movies that used to play now throw the error message... "Can Not Open File".

**Comment by bosxixi** [comment]
it is possible the voltage of the usb for the hard drive not stable, please check that

**Comment by DaytonaXBoxGuy** [comment]
Actually I have been researching this issue further and believe it is an XBox One limitation of 2TB for media drives. Some further testing was done and noticed as soon as the drive was filled past 2TB problems started happening. Once files were deleted to get the drive under 2TB they started playing again. Note: I tested a variety of files on a drive with 2.5TB in use and they all failed. I don't know if Scorpio Player devs can get past this limitation or not. The strange thing is if you mark the drive for games instead of media, it will support up to 18TB overall size. Media purposed drives are absolutely restricted to MBR partitions with less than 2TB on them. Long story short, if you use your XBox One (X, S or original) as a media player, stick to 2TB externals or less. The bigger drives will be unusable past the 2TB mark!

**Comment by bosxixi** [comment]
simple solution, plug in your hard drive into windows pc, use disk manager tool convert MBR to GPT, this will loss all the data you have on the disk
