### ISSUE TITLE
Please add full screen audio visualization option to avoid image burn-in

### ISSUE THREAD

**Issue by ChodaBoy** [ScorpioPlayer/Feedback#15]
Hi, I use this app on my Xbox One to play music while I do other things, including sleep. With the increasing number of OLED displays available, I am concerned about image burn-in (and battery life) caused by a static image on the screen. It would be great if you would add an option to have an old school Winamp style full-screen moving colored lines on a black background style audio visualization.

**Comment by bosxixi** [comment]
v 2.10.1168.0/70 released with this feature for audio file with no Art work.

https://github.com/ScorpioPlayer/Feedback/assets/12491547/16cd7e3f-5724-4f0b-968c-cb693c087a87
