### ISSUE TITLE
No HDR support

### ISSUE THREAD

**Issue by balvolkan** [ScorpioPlayer/Feedback#16]
I have bought the software to watch hdr movies, apparently not supporting hdr10 or hdr. 

You advertise it is playing HDR this is not true!

**Comment by bosxixi** [comment]
Windows 10/11 PC or Xbox. 
PC version are fully supported. 
Xbox unable to activate HDR mode in the TV

**Comment by bosxixi** [comment]
Hello:

![image](https://github.com/ScorpioPlayer/Feedback/assets/12491547/40f9616c-5215-4a74-a34d-614fcb79a967)


On Xbox Device recommend to use Game Mode and HDR Tone Mapping feature:

https://blog.scorpioplayer.com/blog/how-to-use-hdr-tone-mapping-feature-for-scorpio-player-app/

Game Mode:

https://blog.scorpioplayer.com/blog/scorpio-player-on-xbox-series-sx-game-mode/
