### ISSUE TITLE
Progress Bar Opacity at start

### ISSUE THREAD

**Issue by rn23x0** [ScorpioPlayer/Feedback#18]
If you set the opacity to any value, the next time the app gets started it will not apply until the cursor moves over the progress bar. 

Also there could be an option to not reset the location of the progress bar at each start of the app, if you moved it to another location before.

**Comment by bosxixi** [comment]
Fixed in v2.10.6.

you can check the "Remember Transport Control Position" option from context menu by right click the transport control.
