### ISSUE TITLE
WebDev server function

### ISSUE THREAD

**Issue by nyaaso** [ScorpioPlayer/Feedback#22]
Hello.

I'd like to request a function.

I would like to add more Webdev functions.

https option
port option

And the condition of Korean translation is bad.

Did you use a translator?

**Comment by bosxixi** [comment]
![image](https://user-images.githubusercontent.com/12491547/198197951-d22ee605-ab30-4e3b-949a-166045c7f395.png)

![image](https://user-images.githubusercontent.com/12491547/198197990-72200a78-72fc-472c-9645-286bb865c66e.png)

New version support what you asked now.

Yes, It is machine translated. would you like to help?
