### ISSUE TITLE
I loved the app but...

### ISSUE THREAD

**Issue by oqiday** [ScorpioPlayer/Feedback#23]
I loved the app but unfortunately I cant change subtitle settings on my xbx one device. Subtitles have blue background and it is really shitty looking one l can't consantrate on the film Im watching please help me with this I don't want to search for another app.

**Comment by bosxixi** [comment]
some file has blue tint background of image subttile, current solution would be use the [Search subtitle panel] download new text-base subtitle from online

**Comment by oqiday** [comment]
I tried at least 10 more subtitles but still remained blue :/

**Comment by oqiday** [comment]
I tried at least 10 more subtitles but still remained blue :/

bosxixi <notifications@github.com>, 29 Nis 2020 Çar, 00:28 tarihinde şunu
yazdı:

**Comment by oqiday** [comment]
I can change it on my computer but I am not be ablo to change it on my
xbox. The background literally kills my eyes :(

oqiday31 <oqboqos@gmail.com>, 29 Nis 2020 Çar, 03:50 tarihinde şunu yazdı:

**Comment by oqiday** [comment]
I think your player for xbox does not support PGS maybe ?

oqiday31 <oqboqos@gmail.com>, 29 Nis 2020 Çar, 04:01 tarihinde şunu yazdı:

**Comment by oqiday** [comment]
Yup thats the problem, it would be very cool if you guys just update the
app lol. Thanks anyways!! Nice app.👍

oqiday31 <oqboqos@gmail.com>, 29 Nis 2020 Çar, 04:27 tarihinde şunu yazdı:

**Comment by bosxixi** [comment]
v2.10.1181.0/70 fixed this issue, thanks for the feedback

before
![before](https://github.com/ScorpioPlayer/Feedback/assets/12491547/0e1c2374-04fb-478b-a24c-0f62649e9226)

after
![after](https://github.com/ScorpioPlayer/Feedback/assets/12491547/9fa42a53-9f5d-4d57-8c05-15117c36421e)
