### ISSUE TITLE
smb协议无法连接？

### ISSUE THREAD

**Issue by sendreams** [ScorpioPlayer/Feedback#24]
smb://192.168.1.21/movie  --> 无效
smb://user:password@192.168.1.21/movie  --> 无效

这两种格式地址播放器都无法连接，但资源管理器可以顺利打开这些远程资源，还请核查。

**Comment by Teachoc** [comment]
我这里的情况是smb能连上，但是有一些文件和文件夹不显示，但同样是UWP版的VLC则完全正常：

- 其中部分文件夹提示拒绝访问(此处VLC提示认证)；
- 文件夹名为`@`开头的未显示（e.g. `@01`）；
- 文件夹中同时包含文件与文件夹时只能够看到文件夹；

**Comment by bosxixi** [comment]
previous SMB feature only support SMB1 and some SMB server is not enabled by default like Synology NAS,

![image](https://github.com/ScorpioPlayer/Feedback/assets/12491547/2b0e086b-5622-496e-8091-546396cd4be6)

or SMB2 instead
update to latest version v2.10.1168.0/70


https://github.com/ScorpioPlayer/Feedback/assets/12491547/d95af0ed-4357-41e8-ba81-a1f8c1ef489d
