### ISSUE TITLE
Subtitle on/off toggle button? Why are URL files in my playlist?

### ISSUE THREAD

**Issue by zhiznnagi** [ScorpioPlayer/Feedback#34]
Hello everyone. I actually wanted to ask a question but it can also be a request/issue if there is no solution I am unaware of currently. 

I just want to know if there is a way to add a button to toggle the subtitles on/off on the control bar. It would make my life a lot easier because I have many videos that have subtitles built in and the default is for them to automatically be on whenever a video starts.

Also, when I open a folder, the playlist doesn't only list video files but also other files sometimes like my URL files. Why? The program can't do anything with URL files, it just causes an error when the player tries to play them in the playlist. I don't want to move or delete my URL files from those folders, I just don't want the Scorpio Player to try to play them or even detect them.

**Comment by bosxixi** [comment]
hi just quick check, have you try 'Close Subtitle' menu item, from the transport control bar, after video started playing.

or maybe there is a settings toggle in the preferences dialog or settings dialogs 'Use Subtitle' or 'Disable Subtitle' settings something like that. not sure there is but we can built one if necessary for sure.

and what is your URL files extensions? maybe next version can exclude those files?

thanks for feedback

**Comment by zhiznnagi** [comment]
Oh I found the way to quickly disable subtitles, thanks!

As for the URLs, they're internet shorcut files, so they end in ".url".

Thanks for the quick reply, I didn't expect that. This is the best video player I have ever used so far.

**Comment by bosxixi** [comment]
where are your folder locate at ? local hard drive? I have tried in my PC, if I drag and drop a folder which contains .url file, it will not appears in the playlist? how do I reproduce this please?

**Comment by bosxixi** [comment]
Thank you for the feedback. I was able to reproduce the issue. It turns out that the WinRT File System API behaves slightly differently on the PC and Xbox. The PC version automatically filters out the .url, while the Xbox does not.

I have fixed this issue with update v2.10.1188.70.
