### ISSUE TITLE
annoying file size pop-up after last update

### ISSUE THREAD

**Issue by zhiznnagi** [ScorpioPlayer/Feedback#35]
Hello. Ever since the last update, I've been seeing the file size of the video that I'm watching popping up repeatedly on the bottom-left of the screen. It's happening on both my Xbox One player and my Windows PC player. Is there a way to stop this or is it a new bug that has to get fixed with another update? Please fix this soon, it's VERY ANNOYING.

picture of the issue: https://ibb.co/QNnbjyn

**Comment by bosxixi** [comment]
yes, new version introduce this issue, keep reporting current memory usage.. fix coming soon, but have to wait for Microsoft to approve new packages submission. thanks for report this. will close this once new version released.

**Comment by zhiznnagi** [comment]
Thanks for the quick reply, and thanks for continuing to update, especially on Xbox One where I use the program every day.

**Comment by bosxixi** [comment]
thanks for the support. new version 2.10.1080 should fixed this issue
