### ISSUE TITLE
Option to automatically turn on loop for short videos?

### ISSUE THREAD

**Issue by zhiznnagi** [ScorpioPlayer/Feedback#36]
Does such an option already exist and I just can't find it? If not, then I would love this option. Maybe give the option to set the minimum time required for loop to turn on. Like:

Automatically loop video [  ] (check box)
     - For any video under: ___1_minute___
     
     
   Or at least have the app remember if I set a video to loop so that it always loops the next time I open it?

**Comment by bosxixi** [comment]
great idea, will consider implement the feature for new version update.

have you tried this transport control button, I have tested it. looks like after close and open the app, this setting still persist
![image](https://user-images.githubusercontent.com/12491547/233568989-73722f76-7f89-4021-a84e-e83d6c89c300.png)

**Comment by zhiznnagi** [comment]
Yes, thank you, but I usually watch a mix of short and long videos, so it can become annoying to cycle through the loop options every time.
