### ISSUE TITLE
How to make subtitles load automatically for any video?

### ISSUE THREAD

**Issue by zhiznnagi** [ScorpioPlayer/Feedback#37]
Some of my videos that I downloaded came with subtitles that open automatically. But I also have videos that have SRT files but every time I open the video I have to always choose the SRT file every time, even if there is only one SRT file and it has the same file name as the video.

**Comment by zhiznnagi** [comment]
Ok thanks, but what about on Xbox One? Is it possible?

**Comment by bosxixi** [comment]
then you need to open the folder which contains both the video file and the same name subtitle file
