### ISSUE TITLE
打开蓝光文件夹报错

### ISSUE THREAD

**Issue by sensty** [ScorpioPlayer/Feedback#38]
![image](https://github.com/ScorpioPlayer/Feedback/assets/24983339/bd42e8c3-da9b-48ff-b9c1-2bb3d1b0fc2b)

**Comment by bosxixi** [comment]
能给个该文件夹截图吗
打开的文件夹下面有 文件夹 BDMV 吗？

**Comment by sensty** [comment]
蓝光文件夹
![image](https://github.com/ScorpioPlayer/Feedback/assets/24983339/9b023749-40de-417d-a24a-001320f607ed)
BDMV文件夹
![image](https://github.com/ScorpioPlayer/Feedback/assets/24983339/10a4b17e-bf80-48cf-b6b7-ea09cd98d008)

**Comment by bosxixi** [comment]
多谢反馈 新版本应该修复了此问题。 

版本大于 v2.10.1175.0

我这边试了 蓝光原盘 ISO 和蓝光文件夹都可以正常打开了

![image](https://github.com/ScorpioPlayer/Feedback/assets/12491547/7eacd5e3-0798-45cf-965e-9e4269f7d28e)
