### ISSUE TITLE
链接OneDrive失败

### ISSUE THREAD

**Issue by starwhite1** [ScorpioPlayer/Feedback#39]
将OneDrive添加到收藏夹中后，左下角报错并显示
Failed to retrieve OneDrive access token. Additional information: AADSTS90002:Tenant '9188040d-6c67-4c5b-
b112-36a304b66dad” not found.Check to make sure you have the correct tenant lD and are signing into the correct cloud.Check with your subscription administrator, this may happen if there are no active subscriptions for the tegant.
Trace ID: b90946cd-9e35-418a-afdf-898c86060901
Correlation ID: 9064cc73-c79d-4617-bb97-2e5698efaa50Timestamp: 2023-08-24 05:47:40Z
请问该如何解决

**Comment by bosxixi** [comment]
![image](https://github.com/ScorpioPlayer/Feedback/assets/12491547/d14fb236-f496-472b-82b9-bc061e3daea4)

你好， 谢谢反馈这个问题，原因是App 在微软的密钥两年后过期了
临时解决方案， 

如果是之前登陆过的 可以点击右上角 三个点 按钮 使用恢复 功能
如果是新帐号添加 就无法解决了， 只能等待 新版本推送修复这个功能

**Comment by bosxixi** [comment]
3.3707 iOS version released.

https://apps.apple.com/us/app/id1617922279?platform=iphone

you can use iOS app to login into onedrive and then backup and restore from PC/Xbox side, if you have SCORPIO+ user account.

**Comment by bosxixi** [comment]
Scorpio Player 2.10.1159.0 released

https://apps.microsoft.com/store/detail/scorpio-player/9NPKQ7SRLV1L
