### ISSUE TITLE
[Bug]收藏夹管理器的“从收藏夹移除”按钮功能无效

### ISSUE THREAD

**Issue by PaTTeeL** [ScorpioPlayer/Feedback#4]
收藏夹中添加的文件，使用收藏夹管理器（也就是弹出窗）的时候，文件可以选中（变成蓝色），但是“从收藏夹移除”按钮无效，请修复。
![image](https://user-images.githubusercontent.com/9150277/50376386-11a54800-0647-11e9-82db-350836e15ef6.png)

另外请教图片中右下角的选单用途是什么？选过本地源和smb作为收藏源，既不是过滤器，也不是列表存储，没找到用法说明。
![image](https://user-images.githubusercontent.com/9150277/50376337-bd01cd00-0646-11e9-9da6-438bea6cf81b.png)

**Comment by bosxixi** [comment]
![fm](https://user-images.githubusercontent.com/12491547/50401075-bf8b3080-07c6-11e9-88c2-92b11531f1b0.PNG)

收藏夹管理器加入其他源的设置开关及链接， 右下角为便捷的多选过滤器。没有正确设置SMB源所以没有显示出来。
