### ISSUE TITLE
[Function]建议增加章节跳转功能

### ISSUE THREAD

**Issue by PaTTeeL** [ScorpioPlayer/Feedback#5]
播放控制栏、“书签/章节”菜单中和热键选项中都缺少上一章、下一章和跳到某一章的跳转功能，每次只能鼠标选择，建议增加章节跳转功能，方便预览和迅速跳转到所需的章节。
![image](https://user-images.githubusercontent.com/9150277/50376418-8d06f980-0647-11e9-8f25-a89dbaca5dec.png)

**Comment by bosxixi** [comment]
菜单中添加 上一章 下一章, 键盘快捷键为 Ctrl +←,  Ctrl +→
