### ISSUE TITLE
[Function]增加部分文件类型的播放关联

### ISSUE THREAD

**Issue by PaTTeeL** [ScorpioPlayer/Feedback#6]
现在设置默认媒体播放器的时候关联的文件类型为mp4、mkv、mpg、avi、flv等，但是3gp、wmv、ts、m2ts等文件未能关联，经测试也能正常播放，能否一并设置进文件关联？使用打开方式也无法找到并选择天蝎播放器，能否增加这些文件类型的关联？

**Comment by bosxixi** [comment]
描述的几个格式会在下个版本添加， 其他更多格式会在之后的版本逐步加上。 不能一次性把所有格式加上的原因是， 会影响微软商店应用审核如果添加的格式不支持会导致无法通过审核， 会影响其他功能及时上线。
