### ISSUE TITLE
[Bug]设置面板中热键页面滚动异常

### ISSUE THREAD

**Issue by PaTTeeL** [ScorpioPlayer/Feedback#7]
在设置面板中，“热键”页面的上下滚动异常，具体表现为：使用鼠标滚轮只能上下滚动3行就无法继续往下查看其它热键设置了，而使用滚动条则只能看到倒数第四条，后面三项热键的设置无法看到，感觉鼠标滚轮和滚动条的控制了两个独立窗体的滚动，烦请修复。
（Surface Pro3，系统：win10 17763.195，屏幕分辨率2160x1440）

**Comment by bosxixi** [comment]
多谢反馈
