### ISSUE TITLE
[Function]左下角显示的搜索进度能否配上总时长？

### ISSUE THREAD

**Issue by PaTTeeL** [ScorpioPlayer/Feedback#8]
如图，能否在进度搜索时，左下角不仅显示当前时间点，也能配上总时长或者剩余时长（若是控制栏最右边的时间也能一并进行选择显示总时长还是剩余时间就更好了），这样比较可以知道总体的进度。
![image](https://user-images.githubusercontent.com/9150277/50376686-795d9200-064b-11e9-9153-590d7cdb2500.png)

**Comment by bosxixi** [comment]
v2.9.62300.0
右键控制栏=>UI/UX=>显示总持续时间，而不是剩余时间。或者直接点击进度条右边的剩余时间文字切换。
