### ISSUE TITLE
Removing Folders from Media Server

### ISSUE THREAD

**Issue by earthnugs** [ScorpioPlayer/Feedback#9]
Is there a way to do this? I was looking to make a specific music folder so only audio files are shared, but I don't see any option to remove previously selected folders, so I'm at a bit of a loss here.

**Comment by bosxixi** [comment]
what media server? scorpio media server? remove? please be specifc? 
do you mean you have a folder which has audios and sub folders?

**Comment by earthnugs** [comment]
I was talking about Scorpio Media Server, yes, but I actually just now realized you can only have one main folder selected at a time, so I see why this was confusing. I thought I had actually added a couple directories into the list, but obviously I was just overriding my previous selection. No need to remove any folders at all! Oops. 

Would it be possible to add a function like that? I have two separate music directories, one on a thumb drive and the other on my internal hard drive. If I could have both of those folders selected at once, that would be cool.

**Comment by bosxixi** [comment]
only version Scorpio Media Server v3 support this feature is Docker version via unix directory mounting

**Comment by bosxixi** [comment]
![image](https://user-images.githubusercontent.com/12491547/198197696-37748b02-5a79-41ae-9f76-6f58364f5951.png)

new version of Scorpio Media Server HTTP Mode now supported multiple folders to share.
